apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/commitHash: 18c83b19e422bba5fee577701aa9259527a95a12
    application.deploy.reform/deploymentNo: calvinapi-DP2
    application.deploy.reform/name: calvinapi
    application.deploy.reform/revision: 2023.03.2
    deploy.reform/domain: reslv.io
    deploy.reform/version: a463dd478a21f2dc41a8ad45a1a54019222c6b94
  creationTimestamp: null
  name: calvinapi
  namespace: qa1
spec:
  components:
  - name: calvinapi-newapi-api
    properties:
      addRevisionLabel: false
      cpu: "0.5"
      exposeType: ClusterIP
      image: nginx
      memory: "200"
      port: 80
      ports:
      - expose: true
        name: http
        port: 80
        protocol: TCP
    type: webservice
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - eks
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
