apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/commitHash: 85bd8d326a0a50754cfc2a28b537ce309feef1c6
    application.deploy.reform/deploymentNo: qc-test-q2-DP2
    application.deploy.reform/name: qc-test-q2
    application.deploy.reform/revision: 2023.03.2
    deploy.reform/domain: reslv.io
    deploy.reform/version: a463dd478a21f2dc41a8ad45a1a54019222c6b94
  creationTimestamp: null
  name: qc-test-q2
  namespace: qa1
spec:
  components:
  - name: qc-test-q2-qc-newhelm-k8s
    properties:
      chart: hello-world
      installTimeout: 10m
      interval: 30s
      pullInterval: 5m
      repoType: helm
      retries: 3
      url: https://helm.github.io/examples
      version: 0.1.0
    type: helm
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - eks
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
